// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4cTvH9awetU6qaNzw1af4X5B6pfz8BMI',
    appId: '1:401855510966:web:ba0c640363197ecdb9e917',
    messagingSenderId: '401855510966',
    projectId: 'soundtrack01',
    authDomain: 'soundtrack01.firebaseapp.com',
    storageBucket: 'soundtrack01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDuDKyIPx_N8_5OTP2FCfDLne7_DDoZcI',
    appId: '1:401855510966:android:539c90bbf56c2525b9e917',
    messagingSenderId: '401855510966',
    projectId: 'soundtrack01',
    storageBucket: 'soundtrack01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATm2p4VnM2QkDF5RitYVIU0asZOh45zGU',
    appId: '1:401855510966:ios:fe5ac1bb3564d770b9e917',
    messagingSenderId: '401855510966',
    projectId: 'soundtrack01',
    storageBucket: 'soundtrack01.appspot.com',
    iosBundleId: 'com.AvilaJ.soundTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATm2p4VnM2QkDF5RitYVIU0asZOh45zGU',
    appId: '1:401855510966:ios:a5faf85e4337b0beb9e917',
    messagingSenderId: '401855510966',
    projectId: 'soundtrack01',
    storageBucket: 'soundtrack01.appspot.com',
    iosBundleId: 'com.example.soundTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4cTvH9awetU6qaNzw1af4X5B6pfz8BMI',
    appId: '1:401855510966:web:4ebbd5155c1ddceab9e917',
    messagingSenderId: '401855510966',
    projectId: 'soundtrack01',
    authDomain: 'soundtrack01.firebaseapp.com',
    storageBucket: 'soundtrack01.appspot.com',
  );
}
